version: '3.4'

services:
    php:
        volumes:
            - .:/usr/src/app
            - $HOME/work:/$HOME/work
        environment:
            NEO4J_URL: bolt://neo4j
        user: 1000:1000

    neo4j:
        environment:
            NEO4J_AUTH: none
        ports:
            - 7474:7474
            - 7687:7687


